version: '3.7'

services:
  eureka-server:
    build: ./
    image: "eureka-server"
    ports:
      - "8761:8761"
    environment:
      - TZ=America/Sao_Paulo

networks:
  default:
    external:
      name: gsn_network
